export const COMBO_OFFER_RULES = [
  { id: "offer_1", label: "Flat ₹200 OFF", type: "FLAT", value: 200, condition: { starter: "Masala Fries With Cheese Coated", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_2", label: "30% OFF", type: "PERCENT", value: 30, condition: { starter: "Chicken Popcorn", main: "Creamy Baked Chicken" } },
  { id: "offer_3", label: "Flat ₹150 OFF", type: "FLAT", value: 150, condition: { starter: "Antipasto Garlic Bread", main: "Corn Rice With Veggies" } },
  { id: "offer_4", label: "25% OFF", type: "PERCENT", value: 25, condition: { starter: "Paneer Tikka", main: "Cottage Cheese Shashlik" } },
  { id: "offer_5", label: "Flat ₹100 OFF", type: "FLAT", value: 100, condition: { starter: "Cheese Loaded Nachos With Salsa", main: "Chicken Parmigiana" } },
  { id: "offer_6", label: "20% OFF", type: "PERCENT", value: 20, condition: { starter: "Veg Quesadilla", main: "Tangy Crispy Chicken" } },
  { id: "offer_7", label: "Flat ₹250 OFF", type: "FLAT", value: 250, condition: { starter: "Chicken Wings", main: "Fish Steak" } },
  { id: "offer_8", label: "15% OFF", type: "PERCENT", value: 15, condition: { starter: "Cheese Balls Corn", main: "Corn Rice With Veggies" } },
  { id: "offer_9", label: "Flat ₹120 OFF", type: "FLAT", value: 120, condition: { starter: "Mushroom 65", main: "Cottage Cheese Shashlik" } },

  { id: "offer_10", label: "18% OFF", type: "PERCENT", value: 18, condition: { starter: "Paneer 65", main: "Chicken Parmigiana" } },
  { id: "offer_11", label: "Flat ₹180 OFF", type: "FLAT", value: 180, condition: { starter: "Chicken Tikka", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_12", label: "22% OFF", type: "PERCENT", value: 22, condition: { starter: "Mushroom Tikka", main: "Corn Rice With Veggies" } },
  { id: "offer_13", label: "Flat ₹160 OFF", type: "FLAT", value: 160, condition: { starter: "Chicken Cheese Balls", main: "Creamy Baked Chicken" } },
  { id: "offer_14", label: "28% OFF", type: "PERCENT", value: 28, condition: { starter: "Chicken 65", main: "Tangy Crispy Chicken" } },
  { id: "offer_15", label: "Flat ₹140 OFF", type: "FLAT", value: 140, condition: { starter: "Fish Fingers", main: "Fish Steak" } },
  { id: "offer_16", label: "17% OFF", type: "PERCENT", value: 17, condition: { starter: "Grilled Chicken", main: "Chicken Parmigiana" } },
  { id: "offer_17", label: "Flat ₹130 OFF", type: "FLAT", value: 130, condition: { starter: "Spicy Chicken Strips", main: "Tangy Crispy Chicken" } },
  { id: "offer_18", label: "19% OFF", type: "PERCENT", value: 19, condition: { starter: "Crispy Chicken Breast", main: "Creamy Baked Chicken" } },
  { id: "offer_19", label: "Flat ₹210 OFF", type: "FLAT", value: 210, condition: { starter: "Prawn 65", main: "Fish Steak" } },

  { id: "offer_20", label: "16% OFF", type: "PERCENT", value: 16, condition: { starter: "Cheese Loaded Potato", main: "Corn Rice With Veggies" } },
  { id: "offer_21", label: "Flat ₹110 OFF", type: "FLAT", value: 110, condition: { starter: "Eight Treasures", main: "Cottage Cheese Shashlik" } },
  { id: "offer_22", label: "23% OFF", type: "PERCENT", value: 23, condition: { starter: "Hash Browns With Tartar Sauce", main: "Chicken Parmigiana" } },
  { id: "offer_23", label: "Flat ₹170 OFF", type: "FLAT", value: 170, condition: { starter: "Veg Quesadilla", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_24", label: "21% OFF", type: "PERCENT", value: 21, condition: { starter: "Paneer Tikka", main: "Tangy Crispy Chicken" } },
  { id: "offer_25", label: "Flat ₹190 OFF", type: "FLAT", value: 190, condition: { starter: "Chicken Wings", main: "Creamy Baked Chicken" } },

  { id: "offer_26", label: "14% OFF", type: "PERCENT", value: 14, condition: { starter: "Masala Fries With Cheese Coated", main: "Fish Steak" } },
  { id: "offer_27", label: "Flat ₹220 OFF", type: "FLAT", value: 220, condition: { starter: "Chicken Popcorn", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_28", label: "26% OFF", type: "PERCENT", value: 26, condition: { starter: "Chicken 65", main: "Chicken Parmigiana" } },
  { id: "offer_29", label: "Flat ₹125 OFF", type: "FLAT", value: 125, condition: { starter: "Mushroom 65", main: "Corn Rice With Veggies" } },
  { id: "offer_30", label: "24% OFF", type: "PERCENT", value: 24, condition: { starter: "Paneer 65", main: "Cottage Cheese Shashlik" } },

  { id: "offer_31", label: "Flat ₹155 OFF", type: "FLAT", value: 155, condition: { starter: "Cheese Balls Corn", main: "Tangy Crispy Chicken" } },
  { id: "offer_32", label: "18% OFF", type: "PERCENT", value: 18, condition: { starter: "Chicken Tikka", main: "Fish Steak" } },
  { id: "offer_33", label: "Flat ₹135 OFF", type: "FLAT", value: 135, condition: { starter: "Spicy Chicken Strips", main: "Chicken Parmigiana" } },
  { id: "offer_34", label: "27% OFF", type: "PERCENT", value: 27, condition: { starter: "Grilled Chicken", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_35", label: "Flat ₹165 OFF", type: "FLAT", value: 165, condition: { starter: "Chicken Cheese Balls", main: "Creamy Baked Chicken" } },

  { id: "offer_36", label: "20% OFF", type: "PERCENT", value: 20, condition: { starter: "Fish Fingers", main: "Tangy Crispy Chicken" } },
  { id: "offer_37", label: "Flat ₹145 OFF", type: "FLAT", value: 145, condition: { starter: "Prawn 65", main: "Chicken Parmigiana" } },
  { id: "offer_38", label: "22% OFF", type: "PERCENT", value: 22, condition: { starter: "Chicken Wings", main: "Cottage Cheese Shashlik" } },
  { id: "offer_39", label: "Flat ₹175 OFF", type: "FLAT", value: 175, condition: { starter: "Chicken Popcorn", main: "Fish Steak" } },
  { id: "offer_40", label: "19% OFF", type: "PERCENT", value: 19, condition: { starter: "Paneer Tikka", main: "Creamy Baked Chicken" } },

  { id: "offer_41", label: "Flat ₹115 OFF", type: "FLAT", value: 115, condition: { starter: "Cheese Loaded Nachos With Salsa", main: "Corn Rice With Veggies" } },
  { id: "offer_42", label: "23% OFF", type: "PERCENT", value: 23, condition: { starter: "Veg Quesadilla", main: "Fish Steak" } },
  { id: "offer_43", label: "Flat ₹195 OFF", type: "FLAT", value: 195, condition: { starter: "Chicken 65", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_44", label: "21% OFF", type: "PERCENT", value: 21, condition: { starter: "Mushroom Tikka", main: "Tangy Crispy Chicken" } },
  { id: "offer_45", label: "Flat ₹185 OFF", type: "FLAT", value: 185, condition: { starter: "Chicken Tikka", main: "Chicken Parmigiana" } },

  { id: "offer_46", label: "25% OFF", type: "PERCENT", value: 25, condition: { starter: "Grilled Chicken", main: "Fish Steak" } },
  { id: "offer_47", label: "Flat ₹205 OFF", type: "FLAT", value: 205, condition: { starter: "Chicken Wings", main: "Honey Glazed Chicken Steak" } },
  { id: "offer_48", label: "18% OFF", type: "PERCENT", value: 18, condition: { starter: "Paneer 65", main: "Creamy Baked Chicken" } },
  { id: "offer_49", label: "Flat ₹135 OFF", type: "FLAT", value: 135, condition: { starter: "Eight Treasures", main: "Chicken Parmigiana" } },
  { id: "offer_50", label: "20% OFF", type: "PERCENT", value: 20, condition: { starter: "Masala Fries With Cheese Coated", main: "Cottage Cheese Shashlik" } }
];